<a href="https://colab.research.google.com/github/sanju492/first_project/blob/main/SANJU_DSAB7_and_pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

 1,Create a NumPy array with values from 10 to 49 (inclusive).

● Reshape it into a 4x10 matrix.

● Then extract the last column from the reshaped matrix

In [ ]:
import numpy as np
arr = np.arange(10, 50)

reshaped_arr = arr.reshape(4, 10)


last_column = reshaped_arr[:, -1]

print( reshaped_arr)
print(last_column)


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[19 29 39 49]


2,Create two 3×3 matrices:

One filled with all 5s , One with values from 1 to 9

● Add the two matrices

● Multiply them element-wise

● Then find the transpose of the result

In [ ]:
M1= np.full((3, 3), 5)
M2 = np.arange(1, 10).reshape(3, 3)
print(M1)
print(M2)

add= M1+M2
print(add)

mult =M1*M2
print(mult)

trans = np.transpose(mult)
print(trans)


[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]


3,Create a NumPy array of 15 random integers between 10 and 100.

● Replace all values greater than 50 with -1

● Count how many values were replaced.

In [ ]:
A6= np.random.randint(10, 101, size=15)
A6


array([52, 64, 33, 30, 52, 86, 87, 25, 93, 61, 39, 41, 45, 24, 66])

In [ ]:
A6u = np.where(A6 > 50, -1,A6)
A6u

array([-1, -1, 33, 30, -1, -1, -1, 25, -1, -1, 39, 41, 45, 24, -1])

In [ ]:
A61 = np.sum(A6u == -1)
A61

np.int64(8)

 4, Generate a 5×4 array with random values between 0 and 1 (float).

● Find the row with the maximum sum of values.

● Normalize each row using the formula:

In [ ]:
A7=np.random.random((5,4))
A7

array([[0.88346437, 0.82601906, 0.20269278, 0.116504  ],
       [0.63262187, 0.23520044, 0.72687438, 0.41696259],
       [0.26222233, 0.35457852, 0.44348161, 0.53976096],
       [0.84095522, 0.6092141 , 0.38383815, 0.11369326],
       [0.98995169, 0.61604094, 0.99977208, 0.14495715]])

In [ ]:
row_sum=np.sum(A7,axis=1)
np.argmax(row_sum)

np.int64(4)

In [ ]:
min_row=np.min(A7,axis=1,keepdims=True)
max_row=np.max(A7,axis=1,keepdims=True)
normalized=(A7-min_row)/(max_row-min_row)
normalized

array([[1.        , 0.92510003, 0.11237709, 0.        ],
       [0.80830282, 0.        , 1.        , 0.36968026],
       [0.        , 0.33276876, 0.65309568, 1.        ],
       [1.        , 0.68135124, 0.37145472, 0.        ],
       [0.98851168, 0.55109449, 1.        , 0.        ]])

5,. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])

● Find all unique elements

● Find the duplicates (elements that appear more than once)

In [ ]:
arr =np.array([1,3,5,3,7,9,1,5,5])
U =np.unique(arr)
U

array([1, 3, 5, 7, 9])

In [ ]:
elements, counts = np.unique(arr, return_counts=True)
duplicates = elements[counts > 1]
duplicates


array([1, 3, 5])

6, Create a 6×6 NumPy array with values from 1 to 36.

● Extract the middle 4×4 submatrix.

● Then extract all even numbers from this submatrix.

In [ ]:
arr1 = np.arange(1, 37).reshape(6, 6)
submatrix = arr1[1:5, 1:5]

even_numbers = submatrix[submatrix % 2 == 0]


print("Original 6×6 Array:\n", arr)
print("\nMiddle 4×4 Submatrix:\n", submatrix)
print("\nEven Numbers from Submatrix:\n", even_numbers)



Original 6×6 Array:
 [1 3 5 3 7 9 1 5 5]

Middle 4×4 Submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even Numbers from Submatrix:
 [ 8 10 14 16 20 22 26 28]


7,Generate an array of shape (3, 4) with values from 0 to 11.

● Reshape it to (2, 6)

● Then flatten it into a 1D array

● Convert the 1D array back to shape (4, 3)

In [ ]:
arr2 = np.arange(12).reshape(3, 4)


reshaped1 = arr2.reshape(2,6)

flattened = reshaped1.flatten()

reshaped2 = flattened.reshape(4, 3)


print("Original (3×4) Array:\n", arr2)
print("\nReshaped to (2×6):\n", reshaped1)
print("\nFlattened to 1D:\n", flattened)
print("\nReshaped to (4×3):\n", reshaped2)



Original (3×4) Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2×6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened to 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to (4×3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8, Create an array: a = np.array([[1, 2], [3, 4]])

● Append a new row [5, 6]

● Then append a new column [7, 8, 9]

In [ ]:

a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.vstack([a, [5, 6]])
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
new_col = np.array([7, 8, 9]).reshape(-1, 1)
a = np.hstack([a, new_col])
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

9,a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.array([7, 8, 9])

● Join them into a single array

● Reshape the result into a 3×3 matrix

● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

J = np.concatenate([a, b, c]) #used to combine the arrays
J


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matrix = J.reshape(3, 3)#matrix
matrix



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
D = np.diag(matrix)#daigonal
D

array([1, 5, 9])

10, Create a NumPy array of integers from 1 to 20.

● Extract all values that are divisible by 3 or 5.

● Count how many such values exist.

In [ ]:
arr5 = np.arange(1, 21)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
filtered = arr[(arr % 3 == 0) | (arr % 5 == 0)]
filtered

array([ 0,  3,  5,  6,  9, 10])

In [ ]:
C = filtered.size # count
C

6

# **PANDAS**

1. Load the Titanic dataset and display the first 10 rows.


In [ ]:
import pandas as pd
import seaborn as sns
data = sns.load_dataset('titanic')

data.head()


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

2,Find the number of missing values in each column.

In [ ]:
data.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

3,Find the percentage of passengers who survived, grouped by gender

In [ ]:
percentage = titanic.groupby('sex')['survived'].mean() * 100
percentage.round(2)


sex
female    74.20
male      18.89
Name: survived, dtype: float64

4,Find the average, median, and standard deviation of passenger ages.

In [ ]:
titanic = sns.load_dataset('titanic')
ages = titanic['age'].dropna()

average_age = ages.mean()
median_age = ages.median()
std_dev_age = ages.std()


print("Average Age:", average_age)
print("Median Age:", median_age)
print("Standard Deviation of Age:", std_dev_age)


Average Age: 29.69911764705882
Median Age: 28.0
Standard Deviation of Age: 14.526497332334044


5, Count how many passengers were in each class (pclass).

In [ ]:
pclass=data['pclass']
pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

6,Show all passengers who were female, under age 18, and survived.

In [ ]:
survived_female = data[(data['sex'] == 'female') & (data['age'] < 18) & (data['survived'] == 1)]
display(survived_female)

survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

7,Replace missing age values with the median age

In [ ]:

age.fillna(median_age,inplace=True)
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

8, Create a column age_group with values:

a. 'Child' for age < 18

b. 'Adult' for age 18–60

c. 'Senior' for age > 60

d. Use: apply() or np.where() or custom function

In [ ]:
titanic['age'] = titanic['age'].fillna(titanic['age'].median())

def age_group(age):
    if age < 18:
        return 'Child'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Senior'


titanic['age_group'] = titanic['age'].apply(age_group)


print(titanic[['age', 'age_group']].head())


    age age_group
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult


9,Display the top 5 passengers who paid the highest fare.

In [ ]:

top_fares = titanic.sort_values(by='fare', ascending=False).head(5)
print(top_fares[['fare', 'pclass', 'age', 'sex']])


         fare  pclass   age     sex
679  512.3292       1  36.0    male
258  512.3292       1  35.0  female
737  512.3292       1  35.0    male
88   263.0000       1  23.0  female
438  263.0000       1  64.0    male


10,. Find the average fare paid, grouped by both pclass and sex.

In [ ]:
avg_fare = titanic.groupby(['pclass', 'sex'])['fare'].mean()
print(avg_fare)


pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


11,. Rename the following columns:

a. 'sex' → 'gender'

b. 'fare' → 'ticket_fare'

In [ ]:
itanic = titanic.rename(columns={
    'sex': 'gender',
    'fare': 'ticket_fare'
})

print(titanic.columns)


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')


12,. Count the number of passengers who survived and didn’t survive, grouped by class.

In [ ]:
survival_counts = titanic.groupby(['pclass', 'survived']).size().unstack()

survival_counts.columns = ['Did Not Survive', 'Survived']

print(survival_counts)


        Did Not Survive  Survived
pclass                           
1                    80       136
2                    97        87
3                   372       119


13,. Find the average age of passengers grouped by both class and gender.

In [ ]:
avg_age = titanic.groupby(['pclass', 'sex'])['age'].mean()

print(avg_age)


pclass  sex   
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: age, dtype: float64
